version: "3.2"

services:

  timer-app-api:
    image: timer-app-api
    build:
      context: .
      dockerfile: timer_app/Dockerfile
    ports:
      - 3001:3000
    environment:
      - CONNECTION_STRING=Host=local-db:5432;Database=sampledb;Username=postgres;Password=mypassword
      - LOCAL_ENV=true
    links:
      - local-db

  timer-app-tests:
    image: timer-app-tests
    build:
      context: .
      dockerfile: timer_app_tests/Dockerfile
    ports:
      - 3001:3000
    # environment:
    #   - CONNECTION_STRING=Host=test-db:5466;Database=sampledb;Username=postgres;Password=mypassword
    #   - LOCAL_ENV=true
    # links:
      # - test-db

  # test-db:
  #   image: postgres:12
  #   container_name: test-db
  #   ports:
  #     - 5466:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=mypassword
  #     - POSTGRES_DB=sampledb

  local-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=sampledb
    ports:
      - 5432:5432

  # sample-database:
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=mypassword
  #     - POSTGRES_DB=sampledb
  #   image: sample-database
  #   build:
  #     context: .
  #     dockerfile: database/Dockerfile
  #   ports:
  #     - 5433:5432