service: timer-app
provider:
  name: aws
  runtime: dotnet6
  memorySize: 2048
  # vpc:
  #   securityGroupIds:
  #     - sg-09b6d6fe6fcc5086a
  #   subnetIds:
  #     - subnet-860e73fc
  #     - subnet-1d23a351
  #     - subnet-2b003142
  region: eu-west-2
  timeout: 300
  # apiGateway:
  #   apiKeys:
  #       - api-key-${self:service}-${self:provider.stage}
  stage: ${opt:stage}

package:
  artifact: ./bin/release/net6.0/timer_app.zip

functions:
  TimerAppApi:
    name: timer-app-api-${self:provider.stage}
    handler: timer_app::timer_app.LambdaEntryPoint::FunctionHandlerAsync
    environment:
      CONNECTION_STRING: Host=${ssm:/timer-app/${self:provider.stage}/db-hostname};Port=${ssm:/timer-app/${self:provider.stage}/db-port};Database=${self:provider.stage};Username=${ssm:/timer-app/${self:provider.stage}/db-username};Password=${ssm:/timer-app/${self:provider.stage}/db-password}
      Auth0_Domain: ${ssm:/timer-app/${self:provider.stage}/auth0-domain}
      Auth0_Audience_AccessToken: ${ssm:/timer-app/${self:provider.stage}/auth0-audience-accessToken}
      Auth0_Audience_IdToken: ${ssm:/timer-app/${self:provider.stage}/auth0-audience-idToken}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          private: false