version: 2.1

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  build-and-test:
      executor: docker-python
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build
            command: docker-compose build timer-app-tests
        - run:
            name: Run tests
            command: docker-compose run timer-app-tests

workflows:
  test-and-deploy: 
    jobs:
      - check-code-formatting
      - build-and-test
