version: 2.1

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  deploy-lambda:
      executor: docker-dotnet
      description: "Deploys API via Serverless"
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install Node.js
            command: |
              curl -sL https://deb.nodesource.com/setup_14.x | bash -
              apt-get update && apt-get install -y nodejs
        - run:
            name: Install serverless CLI
            command: npm i -g serverless
        - run:
          name: Build lambda
            command: |
              cd ./timer_app/
              chmod +x ./build.sh
              ./build.sh
        - run:
            name: Deploy application
            command: |
              cd ./timer_app/
              sls deploy

  check-code-formatting:
      executor: docker-dotnet
      steps:
        - checkout
        - run:
            name: Install dotnet format
            command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
        - run:
            name: Run formatter check
            command: ./dotnet-format-local/dotnet-format --check
  build-and-test:
      executor: docker-python
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build
            command: docker-compose build timer-app-tests
        - run:
            name: Run tests
            command: docker-compose run timer-app-tests

workflows:
  test-and-deploy-development: 
    jobs:
      # - check-code-formatting
      # - build-and-test
      - deploy-lambda
          # requires:
          #     - check-code-formatting
          #     - build-and-test
              # filters:
              #     branches:
              #       only: main

