version: 2.1

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
jobs:
  build-and-test:
      executor: docker-python
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build
            command: docker-compose build timer-app-tests
        - run:
            name: Run tests
            command: docker-compose run timer-app-tests

workflows:
  test-and-deploy: 
    jobs:
      - build-and-test
